### ISSUE TITLE
news page not updating number of artciles

### ISSUE THREAD

**Issue by taskmaker1** [uccser/dthm4kaiako#241] opened 2019-01-31 22:33 UTC
https://www.dthm4kaiako.ac.nz/dtta/news/ 
showing on two articles.

Where on the https://www.dthm4kaiako.ac.nz/dtta/ 
shows four news articles.

**Comment by JackMorganNZ** [comment] 2019-01-31 22:44
Duplicate of #240

**Closed by JackMorganNZ** 2019-01-31 22:44 UTC
